extends RefCounted

const CATALOG := {
	"basic_strike": {
		"display_name": "普通攻击",
		"source": "weapon",
		"sp_cost": 0,
		"mp_cost": 0,
		"time_cost": 60,
		"target": "enemy_single",
		"effects": [{"type": "damage", "amount": 10}],
		"keywords": [],
	},
	"guard": {
		"display_name": "防御",
		"source": "weapon",
		"sp_cost": 0,
		"mp_cost": 0,
		"time_cost": 40,
		"target": "self",
		"effects": [{"type": "guard", "ratio": 0.5}],
		"keywords": [],
	},
	"swift_cut": {
		"display_name": "迅击",
		"source": "weapon",
		"sp_cost": 8,
		"mp_cost": 0,
		"time_cost": 45,
		"target": "enemy_single",
		"effects": [{"type": "damage", "amount": 12}],
		"keywords": [],
	},
	"heavy_slash": {
		"display_name": "重斩",
		"source": "weapon",
		"sp_cost": 18,
		"mp_cost": 0,
		"time_cost": 100,
		"target": "enemy_single",
		"effects": [{"type": "damage", "amount": 26}],
		"keywords": [],
	},
	"flame_arrow": {
		"display_name": "火焰箭",
		"source": "skill",
		"sp_cost": 4,
		"mp_cost": 12,
		"time_cost": 70,
		"target": "enemy_single",
		"effects": [{"type": "damage", "amount": 22}],
		"keywords": [],
	},
	"interrupt_thrust": {
		"display_name": "打断突刺",
		"source": "skill",
		"sp_cost": 12,
		"mp_cost": 0,
		"time_cost": 55,
		"target": "enemy_single",
		"effects": [
			{"type": "damage", "amount": 8},
			{"type": "delay", "amount": 60},
		],
		"keywords": [],
	},
	"ration": {
		"display_name": "干粮",
		"source": "supply",
		"sp_cost": 0,
		"mp_cost": 0,
		"time_cost": 50,
		"target": "self",
		"effects": [{"type": "restore_sp", "amount": 30}],
		"keywords": [],
		"uses": 2,
	},
	"potion": {
		"display_name": "药水",
		"source": "supply",
		"sp_cost": 0,
		"mp_cost": 0,
		"time_cost": 50,
		"target": "self",
		"effects": [{"type": "heal", "amount": 40}],
		"keywords": [],
		"uses": 1,
	},
	"cave_wolf_strike": {
		"display_name": "撕咬",
		"source": "weapon",
		"sp_cost": 0,
		"mp_cost": 0,
		"time_cost": 50,
		"target": "enemy_single",
		"effects": [{"type": "damage", "amount": 8}],
		"keywords": [],
	},
	"stone_colossus_strike": {
		"display_name": "石拳",
		"source": "weapon",
		"sp_cost": 0,
		"mp_cost": 0,
		"time_cost": 70,
		"target": "enemy_single",
		"effects": [{"type": "damage", "amount": 12}],
		"keywords": [],
	},
	"stone_colossus_earth_shatter": {
		"display_name": "碎地重击",
		"source": "skill",
		"sp_cost": 0,
		"mp_cost": 0,
		"time_cost": 120,
		"target": "enemy_all",
		"effects": [{"type": "damage", "amount": 30}],
		"keywords": [],
	},
}


static func resolve(card_id: String) -> Dictionary:
	if not CATALOG.has(card_id):
		return {}
	var card: Dictionary = CATALOG[card_id].duplicate(true)
	card["card_id"] = card_id
	return card
